### ISSUE TITLE
Better overview

### ISSUE THREAD

**Issue by Bruddelkopf** [Gamagu/Pong_Issues#3]
### Telled you few weeks ago!!

- Colum „Games played“ between „Points“ and „Cups earned“
- Names of Players under the team names (not in the table)
- The current match day under the table for every week

**Comment by Gamagu** [comment]
48.- Names of Players done (1.0.0+2)

**Comment by Gamagu** [comment]
18.- order of Columns (1.0.0+3)

**Comment by Gamagu** [comment]
60.- added current and last playday in tournament overview (1.0.1)
